"use client";
import { useState } from "react";
type Product={id:number;name:string;category:string;price:number;description:string;imageUrl:string|null;tag:string|null;stock:number;active:boolean};
type Order={id:string;orderNumber:string;createdAt:string;total:number;status:string;paymentStatus:string;shippingName:string;shippingEmail:string};
const blank={name:"",category:"Apparel",price:0,description:"",imageUrl:"",tag:"",stock:0,active:true};
export default function Admin(){
 const[token,setToken]=useState("");const[products,setProducts]=useState<Product[]>([]);const[orders,setOrders]=useState<Order[]>([]);const[form,setForm]=useState<any>(blank);const[editing,setEditing]=useState<number|null>(null);const[tab,setTab]=useState<"products"|"orders">("products");const[error,setError]=useState("");const[message,setMessage]=useState("");
 const headers={"content-type":"application/json","x-admin-token":token};
 async function load(){setError("");const[pr,or]=await Promise.all([fetch("/api/products",{headers}),fetch("/api/orders",{headers})]);const pd=await pr.json(),od=await or.json();if(!pr.ok||!or.ok){setError(pd.error||od.error||"Unable to open dashboard.");return}setProducts(pd.products||[]);setOrders(od.orders||[])}
 function edit(p:Product){setEditing(p.id);setForm({...p,imageUrl:p.imageUrl||"",tag:p.tag||""});window.scrollTo({top:0,behavior:"smooth"})}function reset(){setEditing(null);setForm(blank)}
 async function save(e:React.FormEvent){e.preventDefault();setError("");const r=await fetch(editing?`/api/products/${editing}`:"/api/products",{method:editing?"PUT":"POST",headers,body:JSON.stringify({...form,price:Number(form.price),stock:Number(form.stock)})});const d=await r.json();if(!r.ok){setError(d.error||"Unable to save product.");return}setMessage(editing?"Product updated.":"Product added.");reset();await load()}
 async function remove(id:number){if(!confirm("Delete this product permanently?"))return;const r=await fetch(`/api/products/${id}`,{method:"DELETE",headers});const d=await r.json();if(!r.ok){setError(d.error||"Unable to delete product.");return}setMessage("Product deleted.");await load()}
 return <main className="adminPage"><header className="simpleHeader"><a className="brand" href="/"><img src="/not-logo.png" alt="NoT"/></a><a href="/">← Store</a></header><div className="adminShell">
  <section className="adminIntro"><div><p className="eyebrow">NO T · ADMIN</p><h1>Store management</h1><p className="muted">Manage products, inventory and orders.</p></div><div className="adminLogin"><input value={token} onChange={e=>setToken(e.target.value)} placeholder="ADMIN_TOKEN" type="password"/><button className="primary" onClick={load}>Open dashboard</button></div></section>
  {error&&<p className="formError">{error}</p>}{message&&<p className="formSuccess">{message}</p>}<div className="adminTabs"><button className={tab==="products"?"active":""} onClick={()=>setTab("products")}>Products ({products.length})</button><button className={tab==="orders"?"active":""} onClick={()=>setTab("orders")}>Orders ({orders.length})</button></div>
  {tab==="products"&&<div className="adminColumns"><form className="productForm" onSubmit={save}><h2>{editing?"Edit product":"Add product"}</h2><label>Product name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="adminFormRow"><label>Category<input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Tag<input value={form.tag} onChange={e=>setForm({...form,tag:e.target.value})} placeholder="New / Best Seller"/></label></div><div className="adminFormRow"><label>Price (₹)<input required min="0" step="1" type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Stock<input required min="0" step="1" type="number" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label></div><label>Description<textarea required rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Product image URL<input type="url" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})} placeholder="https://..."/></label><label className="checkLabel"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Visible in store</label><div className="formActions"><button className="primary">{editing?"Update product":"Add product"}</button>{editing&&<button type="button" onClick={reset}>Cancel</button>}</div></form>
  <section className="productManager"><h2>Catalogue</h2>{products.length===0?<div className="empty">Enter your token and open the dashboard.</div>:products.map(p=><article className="productRow" key={p.id}><div className="thumb">{p.imageUrl?<img src={p.imageUrl} alt=""/>:<span>NoT</span>}</div><div className="productInfo"><div><strong>{p.name}</strong>{!p.active&&<em>Hidden</em>}</div><small>{p.category} · ₹{p.price.toLocaleString("en-IN")} · {p.stock} in stock</small></div><div className="rowActions"><button onClick={()=>edit(p)}>Edit</button><button className="danger" onClick={()=>remove(p.id)}>Delete</button></div></article>)}</section></div>}
  {tab==="orders"&&<div className="adminOrders">{orders.length===0?<div className="empty">No orders found.</div>:orders.map(o=><article className="adminOrder" key={o.id}><div><strong>{o.orderNumber}</strong><small>{new Date(o.createdAt).toLocaleString("en-IN")}</small></div><div><strong>₹{o.total.toLocaleString("en-IN")}</strong><small>{o.status} · {o.paymentStatus}</small></div><p>{o.shippingName} · {o.shippingEmail}</p></article>)}</div>}
 </div></main>
}
