"use client";
import { useMemo, useState } from "react";

type Product={id:number;name:string;category:string;price:number;description:string;imageUrl:string|null;tag:string|null;stock:number;active:boolean};
type Order={id:string;orderNumber:string;createdAt:string;total:number;status:string;paymentStatus:string;shippingName:string;shippingEmail:string};
const blank={name:"",category:"Apparel",price:0,description:"",imageUrl:"",tag:"",stock:0,active:true};

export default function Admin(){
 const[token,setToken]=useState("");const[products,setProducts]=useState<Product[]>([]);const[orders,setOrders]=useState<Order[]>([]);const[form,setForm]=useState<any>(blank);const[editing,setEditing]=useState<number|null>(null);const[tab,setTab]=useState<"products"|"orders">("products");const[error,setError]=useState("");const[message,setMessage]=useState("");const[query,setQuery]=useState("");const[busy,setBusy]=useState(false);
 const headers={"content-type":"application/json","x-admin-token":token};
 const visible=useMemo(()=>products.filter(p=>`${p.name} ${p.category} ${p.tag||""}`.toLowerCase().includes(query.toLowerCase())),[products,query]);
 const lowStock=products.filter(p=>p.stock<5).length;
 async function load(){setBusy(true);setError("");setMessage("");try{const[pr,or]=await Promise.all([fetch("/api/products",{headers,cache:"no-store"}),fetch("/api/orders",{headers,cache:"no-store"})]);const pd=await pr.json(),od=await or.json();if(!pr.ok||!or.ok)throw new Error(pd.error||od.error||"Unable to open dashboard.");setProducts(pd.products||[]);setOrders(od.orders||[])}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 function edit(p:Product){setEditing(p.id);setForm({...p,imageUrl:p.imageUrl||"",tag:p.tag||""});setMessage("");document.getElementById("product-editor")?.scrollIntoView({behavior:"smooth",block:"start"})}
 function duplicate(p:Product){setEditing(null);setForm({...p,name:`${p.name} Copy`,imageUrl:p.imageUrl||"",tag:p.tag||""});document.getElementById("product-editor")?.scrollIntoView({behavior:"smooth",block:"start"})}
 function reset(){setEditing(null);setForm(blank)}
 async function request(url:string,method:string,body?:unknown){const r=await fetch(url,{method,headers,body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error||"Update failed.");return d}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await request(editing?`/api/products/${editing}`:"/api/products",editing?"PUT":"POST",{...form,price:Number(form.price),stock:Number(form.stock)});setMessage(editing?"Product updated successfully.":"Product added successfully.");reset();await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function toggle(p:Product){setError("");try{await request(`/api/products/${p.id}`,"PUT",{...p,active:!p.active});setProducts(v=>v.map(x=>x.id===p.id?{...x,active:!x.active}:x));setMessage(p.active?"Product hidden from store.":"Product is now visible in store.")}catch(e:any){setError(e.message)}}
 async function remove(id:number){if(!confirm("Delete this product permanently?"))return;try{await request(`/api/products/${id}`,"DELETE");setProducts(v=>v.filter(p=>p.id!==id));setMessage("Product deleted.")}catch(e:any){setError(e.message)}}
 return <main className="adminPage"><header className="adminHeader"><a href="/" className="adminBrand"><img src="/not-logo-taupe.png" alt="NoT"/></a><div><span>Admin</span><a href="/">View store ↗</a></div></header><div className="adminShell">
  <section className="adminIntro"><div><p className="eyebrow">STORE CONTROL</p><h1>Products & orders</h1></div><div className="adminLogin"><input value={token} onChange={e=>setToken(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Enter ADMIN_TOKEN" type="password"/><button className="primary" disabled={busy||!token} onClick={load}>{busy?"Loading…":"Open dashboard"}</button></div></section>
  {error&&<p className="formError">{error}</p>}{message&&<p className="formSuccess">{message}</p>}
  <div className="adminStats"><div><strong>{products.length}</strong><span>Products</span></div><div><strong>{products.filter(p=>p.active).length}</strong><span>Visible</span></div><div><strong>{lowStock}</strong><span>Low stock</span></div><div><strong>{orders.length}</strong><span>Orders</span></div></div>
  <div className="adminTabs"><button className={tab==="products"?"active":""} onClick={()=>setTab("products")}>Products</button><button className={tab==="orders"?"active":""} onClick={()=>setTab("orders")}>Orders</button></div>
  {tab==="products"&&<div className="adminColumns"><form id="product-editor" className="productForm" onSubmit={save}><div className="editorTitle"><div><p className="eyebrow">{editing?`EDITING #${editing}`:"NEW PRODUCT"}</p><h2>{editing?"Edit product":"Add product"}</h2></div>{editing&&<button type="button" className="iconButton" onClick={reset}>×</button>}</div>
   {form.imageUrl&&<img className="adminImagePreview" src={form.imageUrl} alt="Product preview"/>}<label>Product name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Cotton kurti"/></label><div className="adminFormRow"><label>Category<input required list="categories" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><datalist id="categories"><option>Apparel</option><option>Women</option><option>Essentials</option><option>Accessories</option><option>Lifestyle</option></datalist></label><label>Badge / tag<input value={form.tag} onChange={e=>setForm({...form,tag:e.target.value})} placeholder="New"/></label></div><div className="adminFormRow"><label>Price (₹)<input required min="0" step="1" type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Stock quantity<input required min="0" step="1" type="number" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label></div><label>Description<textarea required rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Product details…"/></label><label>Image URL<input type="url" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})} placeholder="https://..."/></label><label className="checkLabel"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/><span><strong>Visible in store</strong><small>Customers can view and buy this product</small></span></label><div className="formActions"><button className="primary" disabled={busy}>{busy?"Saving…":editing?"Save changes":"Add product"}</button><button type="button" onClick={reset}>Clear</button></div></form>
   <section className="productManager"><div className="catalogueHead"><div><p className="eyebrow">CATALOGUE</p><h2>All products</h2></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products…"/></div>{products.length===0?<div className="empty">Enter the admin token to load products.</div>:visible.length===0?<div className="empty">No matching products.</div>:visible.map(p=><article className="productRow" key={p.id}><div className="thumb">{p.imageUrl?<img src={p.imageUrl} alt=""/>:<span>NoT</span>}</div><div className="productInfo"><div><strong>{p.name}</strong><em className={p.active?"live":"hidden"}>{p.active?"Live":"Hidden"}</em></div><small>{p.category} · ₹{p.price.toLocaleString("en-IN")}</small><small className={p.stock<5?"stockLow":""}>{p.stock} in stock</small></div><div className="rowActions"><button className="editAction" onClick={()=>edit(p)}>Edit</button><button onClick={()=>toggle(p)}>{p.active?"Hide":"Show"}</button><button onClick={()=>duplicate(p)}>Copy</button><button className="danger" onClick={()=>remove(p.id)}>Delete</button></div></article>)}</section></div>}
  {tab==="orders"&&<div className="adminOrders">{orders.length===0?<div className="empty">No orders found.</div>:orders.map(o=><article className="adminOrder" key={o.id}><div><strong>{o.orderNumber}</strong><small>{new Date(o.createdAt).toLocaleString("en-IN")}</small></div><div><strong>₹{o.total.toLocaleString("en-IN")}</strong><small>{o.status} · {o.paymentStatus}</small></div><p>{o.shippingName} · {o.shippingEmail}</p></article>)}</div>}
 </div></main>
}
