"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
type Product={id:number;name:string;category:string;price:number;description:string;tag?:string;imageUrl?:string|null;stock:number};

export default function Home(){
 const[category,setCategory]=useState("All");const[query,setQuery]=useState("");const[cart,setCart]=useState<number[]>([]);const[cartOpen,setCartOpen]=useState(false);const[products,setProducts]=useState<Product[]>([]);const[loading,setLoading]=useState(true);
 useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem("not-cart")||"[]"))}catch{} fetch("/api/products",{cache:"no-store"}).then(r=>r.json()).then(d=>setProducts(d.products||[])).finally(()=>setLoading(false))},[]);
 useEffect(()=>{localStorage.setItem("not-cart",JSON.stringify(cart))},[cart]);
 const categories=useMemo(()=>["All",...Array.from(new Set(products.map(p=>p.category)))],[products]);
 const visible=useMemo(()=>products.filter(p=>(category==="All"||p.category===category)&&`${p.name} ${p.description} ${p.category}`.toLowerCase().includes(query.toLowerCase())),[products,category,query]);
 const cartProducts=cart.map(id=>products.find(p=>p.id===id)!).filter(Boolean);const total=cartProducts.reduce((s,p)=>s+p.price,0);const money=(v:number)=>`₹${v.toLocaleString("en-IN")}`;
 function chooseCategory(name:string){setCategory(categories.includes(name)?name:"All");document.getElementById("shop")?.scrollIntoView({behavior:"smooth"})}
 return <main className="editorialSite">
  <div className="announcement">FREE SHIPPING ON ORDERS ABOVE ₹1,499</div>
  <header className="editorialHeader"><a href="#" className="editorialBrand"><img src="/not-logo-taupe.png" alt="NoT — Need of Time"/></a><nav><a href="#new">New in</a><a href="#shop">Shop</a><a href="#collections">Collections</a><a href="#story">Our story</a><a href="#contact">Contact</a></nav><button className="miniBag" onClick={()=>setCartOpen(true)}>Bag <span>{cart.length}</span></button></header>
  <section className="editorialHero" id="new"><div className="heroEditorialCopy"><p className="redEyebrow">THE EVERYDAY EDIT</p><h1>Effortless style,<br/>made for now.</h1><p>Comfort-led women’s essentials designed to move with your day—minimal silhouettes, soft fabrics and timeless tones.</p><a className="squareButton" href="#shop">SHOP NEW ARRIVALS</a></div><div className="heroArt"><div className="heroArch"><div className="heroLogoFrame"><img src="/not-logo-taupe.png" alt="NoT — Need of Time"/><span>Soft tailoring. Everyday confidence.</span></div></div></div></section>
  <section className="collectionSection" id="collections"><p className="redEyebrow centered">SHOP YOUR STYLE</p><h2>Made for every moment</h2><p className="sectionNote">Clean silhouettes. Easy layers. Uncomplicated dressing.</p><div className="collectionTiles"><button className="collectionTile tileOne" onClick={()=>chooseCategory("Apparel")}><span>Everyday Essentials →</span></button><button className="collectionTile tileTwo" onClick={()=>chooseCategory("Women")}><span>Workwear Edit →</span></button><button className="collectionTile tileThree" onClick={()=>chooseCategory("Lifestyle")}><span>Weekend Comfort →</span></button></div></section>
  <section className="trendingSection" id="shop"><div className="shopTitle"><div><p className="redEyebrow">CUSTOMER FAVOURITES</p><h2>Trending now</h2></div><input aria-label="Search products" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the collection"/></div><div className="editorialFilters">{categories.map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div>
   {loading?<div className="storeMessage">Loading the collection…</div>:visible.length===0?<div className="storeMessage">No products match your search.</div>:<div className="editorialGrid">{visible.map((p,i)=><article className="editorialCard" key={p.id}><div className={`editorialVisual shade${i%4}`}>{p.tag&&<span className="editorialTag">{p.tag}</span>}{p.imageUrl?<img src={p.imageUrl} alt={p.name}/>:<span className="visualWords">{p.description.split(" ").slice(0,3).join(" ")}</span>}</div><div className="editorialProductInfo"><p>{p.category}</p><h3>{p.name}</h3><div><strong>{money(p.price)}</strong><button disabled={!p.stock} onClick={()=>setCart(v=>[...v,p.id])}>{p.stock?"Add to bag":"Sold out"}</button></div></div></article>)}</div>}
  </section>
  <section className="brandStory" id="story"><div className="storyPanel"><span>Designed for real life.</span></div><div><p className="redEyebrow">OUR PHILOSOPHY</p><h2>Need of Time</h2><p>NoT creates versatile clothing that feels good, looks refined and stays relevant beyond a season. We believe the best wardrobe is the one you reach for every day.</p><a href="#shop">Discover the collection →</a></div></section>
  <footer className="editorialFooter" id="contact"><img src="/not-logo-taupe.png" alt="NoT"/><div><strong>Need of Time</strong><p>Comfort, considered.</p></div><a href="mailto:hello@notbrands.com">Contact us</a></footer>
  {cartOpen&&<div className="overlay" onClick={()=>setCartOpen(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawerHead"><h2>Your bag</h2><button onClick={()=>setCartOpen(false)}>Close</button></div>{!cartProducts.length?<div className="empty">Your bag is empty.</div>:<><div className="cartList">{cartProducts.map((p,i)=><div className="cartItem" key={`${p.id}-${i}`}><div><strong>{p.name}</strong><small>{p.category}</small></div><div><strong>{money(p.price)}</strong><button onClick={()=>setCart(v=>v.filter((_,n)=>n!==i))}>Remove</button></div></div>)}</div><div className="checkout"><div><span>Total</span><strong>{money(total)}</strong></div><Link className="primary full" href="/checkout" onClick={()=>setCartOpen(false)}>Continue to checkout</Link></div></>}</aside></div>}
 </main>
}
